


namespace SimpleParser
{
    /// <summary>
    /// A simple token class. These are generated by Lexer and consumed by Parser.
    /// </summary>
    public class Token<TTokenType> : IToken<TTokenType>
    {
        public Token(TTokenType type, string text)
        {
            TokenType = type;
            _text = text;
        }

        public TTokenType TokenType { get; }

        public string GetText()
        {
            return _text;
        }

        public override string ToString()
        {
            return _text;
        }

        private readonly string _text;

        public static IToken<TTokenType> New(TTokenType tokenType, string text)
        {
            return new Token<TTokenType>(tokenType, text);
        }

        public static IToken<TTokenType> New(TTokenType tokenType, char c)
        {
            return New(tokenType, c.ToString());
        }

        public static IToken<TTokenType> Empty()
        {
            return New(default(TTokenType), null);
        }

        public bool HasValue
        {
            get { return !Equals(TokenType, default(TTokenType)); }
        }

        public bool IsEmpty
        {
            get { return Equals(TokenType, default(TTokenType)); }
        }
    }
}